name: dotnet publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD # environnement déclaré dans Github au niveau du repo qui permet d'accéder aux variables/secrets associés
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Run Publish
        run: dotnet publish --runtime osx-arm64 -o ./dist -f net8.0 --self-contained
      - name: Create Archive
        run: tar -cvf installersample.tar.gz ./dist
      - name: Calculate SHA256
        id: calculate-sha256
        run: |
          sha256=$(shasum -a 256 installersample.tar.gz | awk '{ print $1 }')
          echo "SHA256=$sha256" >> $GITHUB_ENV
      - name: Release pushed tag
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          tag: ${{ github.ref_name }}
          fileName: 'installersample.tar.gz'
        run: |
          gh release create ${tag} \
              "./installersample.tar.gz" \
              --repo="https://github.com/victorprouff/InstallerSample" \
              --title="${tag#v}" \
              --generate-notes
              --notes="SHA256=${SHA256}"
      # - uses: pipe-cd/actions-gh-release@v2.6.0
      #   with:
      #     # tags: v1.0.4
      #     release_file: 'installersample.tar.gz'
      #     token: ${{ secrets.TOKEN }}